from __future__ import annotations

from pathlib import Path

import typer

from beam_abm.decision_function.taxonomy import DEFAULT_COLUMN_TYPES_PATH
from beam_abm.decision_function.workflows.anchor_prototypes import (
    run_anchor_prototype_build_workflow,
    run_anchor_prototype_diagnostics_workflow,
    run_anchor_prototype_reference_effects_full_workflow,
    run_anchor_prototype_reference_effects_workflow,
)
from beam_abm.settings import CSV_FILE_CLEAN, SEED

app = typer.Typer(help="Anchor-based heterogeneity pipeline.")


@app.command("build")
def build_cmd(
    input_csv: Path = typer.Option(CSV_FILE_CLEAN, "--input"),
    outdir: Path = typer.Option(Path("empirical/output/anchors/system"), "--outdir"),
    column_types_path: Path = typer.Option(DEFAULT_COLUMN_TYPES_PATH, "--column-types"),
    features: str | None = typer.Option(None, "--features", help="Comma-separated feature list."),
    country_col: str = typer.Option("country", "--country-col"),
    normalization: str = typer.Option("demean_country_then_global_scale", "--normalization"),
    missingness_threshold: float = typer.Option(0.35, "--missingness-threshold"),
    anchor_k: int = typer.Option(10, "--anchor-k"),
    neighbor_k: int = typer.Option(200, "--neighbor-k"),
    globality_min_countries: int = typer.Option(3, "--globality-min-countries"),
    globality_pi_threshold: float = typer.Option(0.05, "--globality-pi-threshold"),
    globality_pi_factor: float | None = typer.Option(None, "--globality-pi-factor"),
    pca_components: int = typer.Option(0, "--pca-components"),
    pca_variance_target: float = typer.Option(0.97, "--pca-variance-target"),
    tau: float | None = typer.Option(None, "--tau"),
    tau_method: str = typer.Option("knn_quantile", "--tau-method"),
    tau_keff_target: float | None = typer.Option(None, "--tau-keff-target"),
    tau_knn_k: int = typer.Option(10, "--tau-knn-k"),
    tau_quantile: float = typer.Option(0.5, "--tau-quantile"),
    tau_sample_n: int = typer.Option(5000, "--tau-sample-n"),
    seed: int = typer.Option(SEED, "--seed"),
) -> None:
    run_anchor_prototype_build_workflow(
        input_csv=input_csv,
        outdir=outdir,
        column_types_path=column_types_path,
        features=features,
        country_col=country_col,
        normalization=normalization,
        missingness_threshold=missingness_threshold,
        anchor_k=anchor_k,
        neighbor_k=neighbor_k,
        globality_min_countries=globality_min_countries,
        globality_pi_threshold=globality_pi_threshold,
        globality_pi_factor=globality_pi_factor,
        pca_components=pca_components,
        pca_variance_target=pca_variance_target,
        tau=tau,
        tau_method=tau_method,
        tau_keff_target=tau_keff_target,
        tau_knn_k=tau_knn_k,
        tau_quantile=tau_quantile,
        tau_sample_n=tau_sample_n,
        seed=seed,
    )


@app.command("diagnostics")
def diagnostics_cmd(
    input_csv: Path = typer.Option(CSV_FILE_CLEAN, "--input"),
    anchors_dir: Path = typer.Option(Path("empirical/output/anchors/system"), "--anchors-dir"),
    outdir: Path = typer.Option(Path("empirical/output/anchors/diagnostics"), "--outdir"),
    country_col: str = typer.Option("country", "--country-col"),
    missingness_threshold: float = typer.Option(0.35, "--missingness-threshold"),
    normalization: str = typer.Option("demean_country_then_global_scale", "--normalization"),
    coverage_k_grid: str = typer.Option("5,10,15,20,25", "--coverage-k-grid"),
    bootstrap_runs: int = typer.Option(20, "--bootstrap-runs"),
    bootstrap_subsample_frac: float = typer.Option(0.8, "--bootstrap-subsample-frac"),
    globality_pi_threshold: float = typer.Option(0.05, "--globality-pi-threshold"),
    seed: int = typer.Option(SEED, "--seed"),
) -> None:
    run_anchor_prototype_diagnostics_workflow(
        input_csv=input_csv,
        anchors_dir=anchors_dir,
        outdir=outdir,
        country_col=country_col,
        missingness_threshold=missingness_threshold,
        normalization=normalization,
        coverage_k_grid=coverage_k_grid,
        bootstrap_runs=bootstrap_runs,
        bootstrap_subsample_frac=bootstrap_subsample_frac,
        globality_pi_threshold=globality_pi_threshold,
        seed=seed,
    )


@app.command("pe")
def pe_cmd(
    input_csv: Path = typer.Option(CSV_FILE_CLEAN, "--input"),
    anchors_dir: Path = typer.Option(Path("empirical/output/anchors/system"), "--anchors-dir"),
    outdir: Path | None = typer.Option(None, "--outdir"),
    country_col: str = typer.Option("country", "--country-col"),
    target_col: str = typer.Option("protective_behaviour_avg", "--target-col"),
    driver_cols: str | None = typer.Option(None, "--driver-cols"),
    levers: str | None = typer.Option(None, "--levers"),
    lever_config: Path | None = typer.Option(None, "--lever-config"),
    lever_key: str | None = typer.Option(None, "--lever-key"),
    lever_scope: str = typer.Option("policy", "--lever-scope"),
    neighborhood_features: str | None = typer.Option(None, "--neighborhood-features"),
    neighbor_k: int = typer.Option(200, "--neighbor-k"),
    min_n: int = typer.Option(200, "--min-n"),
    oom_percentile: float = typer.Option(0.95, "--oom-percentile"),
    propensity_slices: Path | None = typer.Option(None, "--propensity-slices"),
    propensity_outcome: str | None = typer.Option(None, "--propensity-outcome"),
    propensity_slice_col: str = typer.Option("slice", "--propensity-slice-col"),
    ref_models: str = typer.Option("linear", "--ref-models"),
    xgb_n_estimators: int = typer.Option(300, "--xgb-n-estimators"),
    xgb_max_depth: int = typer.Option(4, "--xgb-max-depth"),
    xgb_learning_rate: float = typer.Option(0.05, "--xgb-learning-rate"),
    xgb_subsample: float = typer.Option(0.8, "--xgb-subsample"),
    xgb_colsample_bytree: float = typer.Option(0.8, "--xgb-colsample-bytree"),
    fallback_min_n: int = typer.Option(300, "--fallback-min-n"),
    fallback_min_delta_z: float = typer.Option(0.25, "--fallback-min-delta-z"),
    fallback_quantiles: str = typer.Option("0.10,0.90", "--fallback-quantiles"),
    fallback_quantiles_wide: str = typer.Option("0.05,0.95", "--fallback-quantiles-wide"),
    fallback_nonzero_quantile: float = typer.Option(0.50, "--fallback-nonzero-quantile"),
    predictor_missingness_threshold: float | None = typer.Option(None, "--predictor-missingness-threshold"),
    seed: int = typer.Option(SEED, "--seed"),
    model_plan: Path = typer.Option(Path("empirical/output/modeling/model_plan.json"), "--model-plan"),
) -> None:
    run_anchor_prototype_reference_effects_workflow(
        input_csv=input_csv,
        anchors_dir=anchors_dir,
        outdir=outdir,
        country_col=country_col,
        target_col=target_col,
        driver_cols=driver_cols,
        levers=levers,
        lever_config=lever_config,
        lever_key=lever_key,
        lever_scope=lever_scope,
        neighborhood_features=neighborhood_features,
        neighbor_k=neighbor_k,
        min_n=min_n,
        oom_percentile=oom_percentile,
        propensity_slices=propensity_slices,
        propensity_outcome=propensity_outcome,
        propensity_slice_col=propensity_slice_col,
        ref_models=ref_models,
        xgb_n_estimators=xgb_n_estimators,
        xgb_max_depth=xgb_max_depth,
        xgb_learning_rate=xgb_learning_rate,
        xgb_subsample=xgb_subsample,
        xgb_colsample_bytree=xgb_colsample_bytree,
        fallback_min_n=fallback_min_n,
        fallback_min_delta_z=fallback_min_delta_z,
        fallback_quantiles=fallback_quantiles,
        fallback_quantiles_wide=fallback_quantiles_wide,
        fallback_nonzero_quantile=fallback_nonzero_quantile,
        predictor_missingness_threshold=predictor_missingness_threshold,
        seed=seed,
        model_plan=model_plan,
    )


@app.command("pe-full")
def pe_full_cmd(
    input_csv: Path = typer.Option(CSV_FILE_CLEAN, "--input"),
    anchors_dir: Path = typer.Option(Path("empirical/output/anchors/system"), "--anchors-dir"),
    outdir: Path = typer.Option(..., "--outdir"),
    country_col: str = typer.Option("country", "--country-col"),
    target_col: str = typer.Option(..., "--target-col"),
    driver_cols: str | None = typer.Option(None, "--driver-cols"),
    levers: str | None = typer.Option(None, "--levers"),
    lever_config: Path | None = typer.Option(None, "--lever-config"),
    lever_key: str | None = typer.Option(None, "--lever-key"),
    lever_scope: str = typer.Option("policy", "--lever-scope"),
    neighborhood_features: str | None = typer.Option(None, "--neighborhood-features"),
    neighbor_k: int = typer.Option(200, "--neighbor-k"),
    min_n: int = typer.Option(200, "--min-n"),
    oom_percentile: float = typer.Option(0.95, "--oom-percentile"),
    off_manifold_method: str = typer.Option("conditional_tail", "--off-manifold-method"),
    conditional_tail_alpha: float = typer.Option(0.05, "--conditional-tail-alpha"),
    conditional_tail_knn_k: int = typer.Option(200, "--conditional-tail-knn-k"),
    propensity_slices: Path | None = typer.Option(None, "--propensity-slices"),
    propensity_outcome: str | None = typer.Option(None, "--propensity-outcome"),
    propensity_slice_col: str = typer.Option("slice", "--propensity-slice-col"),
    ref_models: str = typer.Option("linear", "--ref-models"),
    xgb_n_estimators: int = typer.Option(300, "--xgb-n-estimators"),
    xgb_max_depth: int = typer.Option(4, "--xgb-max-depth"),
    xgb_learning_rate: float = typer.Option(0.05, "--xgb-learning-rate"),
    xgb_subsample: float = typer.Option(0.8, "--xgb-subsample"),
    xgb_colsample_bytree: float = typer.Option(0.8, "--xgb-colsample-bytree"),
    fallback_min_n: int = typer.Option(300, "--fallback-min-n"),
    fallback_min_delta_z: float = typer.Option(0.25, "--fallback-min-delta-z"),
    fallback_quantiles: str = typer.Option("0.10,0.90", "--fallback-quantiles"),
    fallback_quantiles_wide: str = typer.Option("0.05,0.95", "--fallback-quantiles-wide"),
    fallback_nonzero_quantile: float = typer.Option(0.50, "--fallback-nonzero-quantile"),
    predictor_missingness_threshold: float | None = typer.Option(None, "--predictor-missingness-threshold"),
    seed: int = typer.Option(SEED, "--seed"),
    model_plan: Path = typer.Option(Path("empirical/output/modeling/model_plan.json"), "--model-plan"),
    keep_full_eval_profiles: bool = typer.Option(False, "--keep-full-eval-profiles"),
) -> None:
    run_anchor_prototype_reference_effects_full_workflow(
        input_csv=input_csv,
        anchors_dir=anchors_dir,
        outdir=outdir,
        country_col=country_col,
        target_col=target_col,
        driver_cols=driver_cols,
        levers=levers,
        lever_config=lever_config,
        lever_key=lever_key,
        lever_scope=lever_scope,
        neighborhood_features=neighborhood_features,
        neighbor_k=neighbor_k,
        min_n=min_n,
        oom_percentile=oom_percentile,
        off_manifold_method=off_manifold_method,
        conditional_tail_alpha=conditional_tail_alpha,
        conditional_tail_knn_k=conditional_tail_knn_k,
        propensity_slices=propensity_slices,
        propensity_outcome=propensity_outcome,
        propensity_slice_col=propensity_slice_col,
        ref_models=ref_models,
        xgb_n_estimators=xgb_n_estimators,
        xgb_max_depth=xgb_max_depth,
        xgb_learning_rate=xgb_learning_rate,
        xgb_subsample=xgb_subsample,
        xgb_colsample_bytree=xgb_colsample_bytree,
        fallback_min_n=fallback_min_n,
        fallback_min_delta_z=fallback_min_delta_z,
        fallback_quantiles=fallback_quantiles,
        fallback_quantiles_wide=fallback_quantiles_wide,
        fallback_nonzero_quantile=fallback_nonzero_quantile,
        predictor_missingness_threshold=predictor_missingness_threshold,
        seed=seed,
        model_plan=model_plan,
        keep_full_eval_profiles=keep_full_eval_profiles,
    )


if __name__ == "__main__":
    app()
